#!/bin/sh
playerctl --player=spotify metadata --format "{{ artist }} - {{ title }}"
case $BLOCK_BUTTON in
	1) playerctl --player=spotify previous;;
	2) playerctl --player=spotify play-pause;;
	3) playerctl --player=spotify next;;
esac
